name: Render documents with rmarkdown-action
on: 
  push:
    branches: 
      - main
    paths:
      - '*.Rmd'
      - '.github/workflows/*'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write
  
  
  
jobs:
  render-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
        
      - name: Render document
        uses: happyRip/rmarkdown-action@v1.1
        with:
          input_file: main.Rmd
          output_format: html_document
          
      - name: Rename document 
        run: |
          mkdir deploy
          mv main.html deploy/index.html
          
      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: 'deploy'
        
