name: Render documents with rmarkdown-action
on: 
  push:
    branches: 
      - main
    paths:
      - 'main.Rmd'
      - '.github/workflows/*'
jobs:
  render_document:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Render document
        uses: happyRip/rmarkdown-action@v1.1
        with:
          input_file: main.Rmd
          output_format: html_document
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: main
          path: main.html
      - name: Commit files
        run: |
          git config --local core.autocrlf false
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          git add -f *.html && git add -f --renormalize *.html
          git pull origin ${{ github.head_ref }} --autostash --rebase -X ours
          git commit --allow-empty -am "AUTO-GH ACTION: ${{ github.workflow }}"
          NO_PAGER=1 git --no-pager diff HEAD^
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
